### PR TITLE
Ch0: Improve translation

### PR DESCRIPTION
**Pull request by SicroAtGit**
- Some parts of the German sentences were missing in the English sentences

- Sentences split into separate lines

- Removed sentences relevant only to the German text

### CODE REVIEW

**Comment by SicroAtGit** [comment]
I forgot that the branch name needs the suffix `dev` for the HTML file to be created.

**Comment by tajmone** [comment]
> I forgot that the branch name needs the suffix `dev` for the HTML file to be created.

Does it? I don't remember this. Also, the build script doesn't seem to refer to branches either:

https://github.com/tajmone/Git-Buch_EN/blob/alpha-dev/docs_src/build.sh

**Comment by SicroAtGit** [comment]
It's in the hook script:
https://github.com/tajmone/Git-Buch_EN/blob/9cf895c60cde2796ab22f2462e52c8174ae2764e/install-git-hooks.sh#L15
It was your suggestion so that experimental branches can be created that do not create an HTML file on commits.

**Comment by tajmone** [comment]
> It was your suggestion so that experimental branches can be created that do not create an HTML file on commits.

My memory is becoming awful, I just forget things (which is why I annotate everything).

**Comment by SicroAtGit** [comment]
No problem. See #5.

**Comment by tajmone** [comment]
> No problem. See #5.

Right. Bear in mind I haven't been using the hook in this repository. I'll have to keep that in mind when building the Rakefile, just to avoid conflicts with the Asciidoctor invocation options used by Rake and those from the hook — for the risk is that the latter would cause a different HTML doc to override the default.

I'm contrary to redundant tasks, so we'll have to consider changing the hook to invoke Rake directly (with the specific task) once Rake is in place, so we they don't clash.

**Pull request closed without merging**
