### PR TITLE
Ch0: Improve translation

### PR DESCRIPTION
**Pull request by SicroAtGit**
- Some parts of the German sentences were missing in the English sentences

- Sentences split into separate lines

- Removed sentences relevant only to the German text

### CODE REVIEW

**Comment by tajmone** [comment]
Thanks a lot!

> Some parts of the German sentences were missing in the English sentences

That's a problem with automatic translator, I guess. Probably there are other similar sentences too — during the translation work I did my best to compare the German input and the English output, and I did notice that the overall sentences structure seemed reductive, but then (not knowing German) there wasn't much I could do.

I'll do my best to fix pending Issues (images alignment, the last diagram that needs colour fixing, etc.) this week so we can move from Alpha to Beta and publish the Beta HTML doc via GitHub Pages.

I'll also add a Rakefile to handle automation via Rake, and get rid of the shell scripts, because Rake is much better and more powerful.

## Ruby 3

Did you already switch to Ruby 3? I did a couple of months ago, having waited a bit after its release, just to ensure all the tools I work with had been updated to v3 too, which introduces backward breaking changes.

On Windows, when I install a new Ruby MAJOR version, the previous versions are kept on the OS, but only the latest one is the default. Ruby for Windows has a dedicated command line tool (ridk) to switch between Ruby versions in the terminal session, so I can still use those Ruby apps that depend on older versions of Ruby. I'm sure that on Linux there's an equivalent tool to manage multiple Ruby versions.

Whereas Asciidoctor still works with both Ruby 2 and 3, for Rake you'll be needing Ruby 3.

**Comment by SicroAtGit** [comment]
> That's a problem with automatic translator, I guess.

Yes. I notice from the DeepL translations that they are improving all the time. But sometimes I still have to force DeepL not to leave out any (for me) important words.

> Probably there are other similar sentences too

I will check out the other chapters as well.

> I'll do my best to fix pending Issues (images alignment, the last diagram that needs colour fixing, etc.) this week so we can move from Alpha to Beta and publish the Beta HTML doc via GitHub Pages.

Sounds good to me. Then I'll look through chapter 1 today as well. But no hurry.

> I'll also add a Rakefile to handle automation via Rake, and get rid of the shell scripts, because Rake is much better and more powerful.

Ok, good.

> Did you already switch to Ruby 3?

```console
$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

> I'm sure that on Linux there's an equivalent tool to manage multiple Ruby versions.

In a hurry I found [rbenv](https://github.com/rbenv/rbenv).

**Comment by tajmone** [comment]
> In a hurry I found rbenv.

I think that's for a different purpose, like Python's virtualenv, it provides a clean-slate environment for project, i.e. as if you didn't install any gems, etc., which allows you to have different versions of the same gems in different projects.

Unfortunately, rbenv is not available in Ruby for Windows (don't know why, since Python's virtualenv works fine under Win OS), and I'd really like to see it coming in the future.

But I'm not sure that rbenv itself provides the functionality to support multiple Ruby installations —  yes, it does allow you to specify different paths pointing to different Ruby versions, but I think that these need to be already pre-installed.

I think that Ruby for Linux and macOS offers some native commands/way to handle multiple Ruby installations on the same machine, and a means to switch between them — after all, each version has to store and update its own gems separately from the others, since they are incompatible versions.

Ultimately, it's just a matter of using different paths, but there are also a number of environment variables (and default `$PATH`) involved, which is what the Ruby version switching command needs to handle. 

Rbenv offers an even finer control, for it allows a single project to use a clean slate Ruby install by storing all required gems directly into the project, and ignoring the globally installed gems on the OS.

**Comment by SicroAtGit** [comment]
> But I'm not sure that rbenv itself provides the functionality to support multiple Ruby installations — yes, it does allow you to specify different paths pointing to different Ruby versions, but I think that these need to be already pre-installed.

https://github.com/rbenv/rbenv#installing-ruby-versions

Another tool is [rvm](https://github.com/rvm/rvm)

> I think that Ruby for Linux and macOS offers some native commands/way to handle multiple Ruby installations on the same machine, and a means to switch between them

Does not look like it. An additional tool like rvm or rbenv is required.
Under Linux it is also unusual to have several versions of a program installed globally.

**Comment by tajmone** [comment]
Interesting that these tools actually handle installing other Ruby versions.

> Under Linux it is also unusual to have several versions of a program installed globally.

But Python and Ruby should be the exception on any OS, since both v2 and v3 of the languages are still used today. 
Also, Python allows SheBangs in `.py` files to specify the required Python version, if I remember correctly.

I still need to switch to Ruby 2 for some applications which have not been fully ported to Ruby 3. With ridk (and I believe rubyenv too) you can run different applications in different terminal sessions or processes,

**Comment by SicroAtGit** [comment]
For older versions there are packages that have the version in the package name (see [here](https://archlinux.org/packages/?q=ruby)). In this way, multiple versions can also be installed. However, you then have to temporarily change the environment variables manually. The above tools make things easier. The ruby installation does not provide such a tool (i.e. no rubyenv, no `ruby --use-version`, no `ruby --set-default-version` or so).

**Pull request merged**
