### PR TITLE
Ch.4: 1st EN Draft

### PR DESCRIPTION
**Pull request by SicroAtGit**
- [x] Translate chapter with DeepL
- [x] Generate HTML file with AsciiDoctor

@tajmone What is meant by "All XRefs restored" and "All footnotes restored" in your previous commit messages is still not clear to me.

### CODE REVIEW

**Comment by SicroAtGit** [comment]
While looking at the generated HTML file in Firefox, I noticed that some texts are bold formatted, but should not be.
https://github.com/tajmone/Git-Buch_EN/blob/a2a5bce69264f53e878e2bbc82bf24cefd029bd9/docs_src/gitbuch_04.adoc#L1335
For example, the `**` in the above code causes AsciiDoctor to see the second star as a start marker to bold the following text.

**Comment by tajmone** [comment]
> @tajmone What is meant by "All XRefs restored" and "All footnotes restored" in your previous commit messages is still not clear to me.

That refers to the fact that for the draft translation I paste the HTML paragraphs into DeepL, instead of the ADoc source, therefore the resulting text doesn't contain the AsciiDoc macros/attributes for footnotes and cross-references but their expanded version instead.

The original German draft paragraphs (which I comment out after pasting the translation below), on the other hand, do contain the AsciiDoc macros/attributes for footnotes and cross-references.

So, what I do is copy the original macros/attributes from the German paragraph to the English draft, and then "expand" them in the German text by pasting their resolved references from the German HTML.

Here is an example of how it works...

## Footnotes

The original German AsciiDoc:

```asciidoc
Es wurde eine Zeile in einer Datei hinzugefügt und die Datei mit den Unix-Rechten `0644` angelegt.{fn8}
```

the translated draft (from German HTML) via DeepL:

    A line has been added to a file, and the file has been created with Unix permissions `0644`.[8]

As you can see, the footnote in the ADoc source is represented by the attribute `{fn8}` (which at conversion time will be expanded to the footnote macro, and the macro to the actual footnote reference).

The English text contains the expanded footnote macro instead `[8]`, i.e. how the footnote reference will be expanded in the final doc. Note that the fact that both versions carry the same footnote number is only because I chose to use attributes to represent the footnotes.

So, after pasting the EN translation into the source, and commenting out the original DE text, I restore the footnote by copying the attributed from the DE source paragraph, and expand it in the commented out DE text (basically, I swap them):

```asciidoc
////
Es wurde eine Zeile in einer Datei hinzugefügt und die Datei mit den Unix-Rechten `0644` angelegt.[8]
////

A line has been added to a file, and the file has been created with Unix permissions `0644`.{fn8}
```

## X-Refs

With the cross-references it's similar, except that their macro will expand to English in our document because if the section title it refers to has already been translated.

Original DE source:

```asciidoc
Für weitere Informationen siehe <<sec.gitk>>.
```

English translation:

    For further information, see Section 3.6.2, "Gitk".

here, since I've copied the paragraph from German HTML, the cross reference was expanded in German, so DeepL translated the Section title also, This is what we want, because feeding the AsciiDoc macros could lead to bad translation because it would confuse DeepL. The translation of the cross-referenced title doesn't necessary match the translation we chose for it,  but since we'll replace it with a macro we don't have to worry about this.

After pasting and editing, I restore the XRef in the source by replacing it with `<<sec.gitk>>`, and "expand it" in the German comments by pasting over it the way it was rendered in the DE HTML doc (to provide a better reference for proof-readers):

```asciidoc
////
Für weitere Informationen siehe Abschnitt 3.6.2, „Gitk“.
////

For further information, see <<sec.gitk>>.
```

I hope this explanation was helpful.

For more info see Asciidoctor Manual:

- [§27. Cross References][§27]
- [§61. Footnotes][§61]
    + [§61.1. Externalizing a Footnote][§61.1] (using attributes for footnotes)


[§27]: https://asciidoctor.org/docs/user-manual/#xref
[§61]: https://asciidoctor.org/docs/user-manual/#user-footnotes
[§61.1]: https://asciidoctor.org/docs/user-manual/#externalizing-a-footnote

**Comment by tajmone** [comment]
> For example, the `**` in the above code causes AsciiDoctor to see the second star as a start marker to bold the following text.

Using asterisks in AsciiDoc can be tricky due to many different processing rules criss-crossing each other.

There are many ways to solve that, but the safest way is to always use the XML entity (`&ast;` or `&#42;`) for a liter asterisk instead.

In contexts that support attributes expansion, you could also use the [predefined attribute] `{asterisk}` (longer, but more human friendly to read).


[predefined attribute]: https://asciidoctor.org/docs/user-manual/#charref-attributes

**Comment by tajmone** [comment]
@SicroAtGit, I've quickly looked at the committed source and it looks fine: all the XRefs are restored in the English translation, as well as the footnotes.

Expanding them in the German comments isn't mandatory, it's just something I do to provide the German proofread (i.e. _you_) with a better context for comparing the original text with the translation. Feel free to skip that if you wish, what matters is that the footnotes attributes and xrefs macros are restored in the English text, the commented German paragraphs are just being ignored, so no problem there.

As for the minor styles problems (like the asterisks you mentioned above), we can fix those later on too. There are various formatting problems in the source due to Py ADoc vs Ruby ADoc differences, and as a result of some S&R operation which I did (although they broke some formatting in a few places, they fixed many more in general).

It's inevitable that some small issues slip by during this stage, but we'll be proofreading the whole book many times over in the next stages, so I wouldn't worry too much.

Feel free to merge when you're happy with the PR.

**Comment by SicroAtGit** [comment]
Thank you very much for your detailed explanations. I could not remember that you are working with the HTML output. Now I understand what you mean by restoring the formatting. So far I have not noticed any bad translations when I insert the AsciiDoc code directly into DeepL. Only a few AsciiDoc characters need to be corrected each time because they were not completely preserved.

**Comment by tajmone** [comment]
> So far I have not noticed any bad translations when I insert the AsciiDoc code directly into DeepL.

During the early tests with DeepL I did notice that in some rare cases the AsciiDoc source could lead to different translations compared to pasting from the generated HTML doc. Some ADoc macros can break a sentence (e.g. because they contain dots or other punctuation marks), and the HTML docs can provide a better context due to macros being expanded (e.g. the full reference to another Section). 

I also think that the DeepL interface is designed to filter HTML contents and, at the same time, keep into account meaningful formatting (e.g. Headings, emphasis, etc.).

**Comment by SicroAtGit** [comment]
For the next chapter I will take the text from the HTML page and send it to DeepL for translation. I also think it is better this way.

**Pull request merged**
